### ISSUE TITLE
Report unsoundness issues

### ISSUE THREAD

**Issue by pflanze** [dzamkov/fortify#3]
Looking through the Git history, all versions pre 3.0.0 seem to have
unsoundness issues. Discussing this on IRC someone pointed out that
this should be reported via RUSTSEC, so that people get notification
from e.g. their cargo audit or dependabot setups. Especially given
that the old versions haven't been yanked.

Here's how to make a report: 
https://rustsec.org/contributing.html

Given that I'm not a contributor and haven't even used the crate yet,
I'm not the best at formulating the report. Do you mind doing it?

**Comment by dzamkov** [comment]
While an informational advisory would technically be appropriate according to RustSec's criteria, I don't think there is much value in this case. The affected versions have less than 500 total downloads between them and the vast majority of those are probably from bots. There's a small chance anyone would even see the advisory, let alone discover an exploitable security vulnerability in actively-used software because of it.

I'm not going to write up an advisory, partially because I don't feel its worth the effort and partially because I wouldn't feel comfortable having a RustSec reviewer spend their time on something which I believe has such a small chance of exposing a security issue. But if you (or anyone else reading this issue) disagrees, you're always free to submit the advisory yourself.

The affected versions have intentionally not been yanked following the guidance of [The Cargo Book](https://doc.rust-lang.org/cargo/commands/cargo-yank.html#when-to-yank).
